# Generated by Django 4.2 on 2023-12-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcgaAccIsoformsFpkmCufflinks',
            fields=[
                ('isoform_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stage_1', models.CharField(blank=True, max_length=348, null=True)),
                ('stage_2', models.CharField(blank=True, max_length=1404, null=True)),
                ('stage_3', models.CharField(blank=True, max_length=606, null=True)),
                ('stage_4', models.CharField(blank=True, max_length=560, null=True)),
                ('all_stage', models.CharField(blank=True, max_length=1962, null=True)),
            ],
            options={
                'db_table': 'TCGA_ACC_isoforms_FPKM_Cufflinks',
                'managed': False,
            },
        ),
    ]
