# Generated by Django 4.2 on 2023-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtclashHybFinalWeb',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clash_read', models.TextField(blank=True, db_column='CLASH Read', null=True)),
                ('region_on_clash_read_identified_as_regulator_rna', models.TextField(blank=True, db_column='Region on CLASH Read identified as Regulator RNA', null=True)),
                ('region_on_clash_read_identified_as_target_rna', models.TextField(blank=True, db_column='Region on CLASH Read identified as Target RNA', null=True)),
                ('read_count', models.BigIntegerField(blank=True, db_column='Read Count', null=True)),
                ('regulator_rna_name', models.TextField(blank=True, db_column='Regulator RNA Name', null=True)),
                ('regulator_rna_sequence', models.TextField(blank=True, db_column='Regulator RNA Sequence', null=True)),
                ('regulator_rna_region_found_in_clash_read', models.TextField(blank=True, db_column='Regulator RNA Region Found in CLASH Read', null=True)),
                ('target_rna_name', models.TextField(blank=True, db_column='Target RNA Name', null=True)),
                ('target_rna_region_found_in_clash_read', models.TextField(blank=True, db_column='Target RNA Region Found in CLASH Read', null=True)),
                ('pirscan_min_ex_binding_site', models.TextField(blank=True, db_column='pirscan min_ex binding site', null=True)),
                ('pirscan_min_ex_target_sequence', models.TextField(blank=True, db_column='pirscan min_ex Target sequence', null=True)),
                ('pirscan_min_ex_score', models.FloatField(blank=True, db_column='pirscan min_ex score', null=True)),
                ('pirscan_max_ex_binding_site', models.TextField(blank=True, db_column='pirscan max_ex binding site', null=True)),
                ('pirscan_max_ex_target_sequence', models.TextField(blank=True, db_column='pirscan max_ex Target sequence', null=True)),
                ('pirscan_max_ex_score', models.FloatField(blank=True, db_column='pirscan max_ex score', null=True)),
                ('rnaup_min_ex_regulator_rna_sequence', models.TextField(blank=True, db_column='RNAup min_ex Regulator RNA sequence', null=True)),
                ('rnaup_min_ex_target_rna_sequence', models.TextField(blank=True, db_column='RNAup min_ex Target RNA sequence', null=True)),
                ('rnaup_min_ex_binding_site', models.TextField(blank=True, db_column='RNAup min_ex binding site', null=True)),
                ('rnaup_min_ex_score', models.FloatField(blank=True, db_column='RNAup min_ex score', null=True)),
                ('rnaup_max_ex_regulator_rna_sequence', models.TextField(blank=True, db_column='RNAup max_ex Regulator RNA sequence', null=True)),
                ('rnaup_max_ex_target_rna_sequence', models.TextField(blank=True, db_column='RNAup max_ex Target RNA sequence', null=True)),
                ('rnaup_max_ex_binding_site', models.TextField(blank=True, db_column='RNAup max_ex binding site', null=True)),
                ('rnaup_max_ex_score', models.FloatField(blank=True, db_column='RNAup max_ex score', null=True)),
                ('d', models.TextField(blank=True, db_column='D', null=True)),
                ('m', models.TextField(blank=True, db_column='M', null=True)),
                ('wt_wago_pirscan_min_ex25_22g', models.FloatField(blank=True, db_column='WT_WAGO_pirscan min_ex25_22G', null=True)),
                ('wt_wago_pirscan_max_ex25_22g', models.FloatField(blank=True, db_column='WT_WAGO_pirscan max_ex25_22G', null=True)),
                ('wt_wago_rnaup_min_ex25_22g', models.FloatField(blank=True, db_column='WT_WAGO_RNAup min_ex25_22G', null=True)),
                ('wt_wago_rnaup_max_ex25_22g', models.FloatField(blank=True, db_column='WT_WAGO_RNAup max_ex25_22G', null=True)),
                ('mutation_count', models.BigIntegerField(blank=True, null=True)),
                ('mutation_pos', models.TextField(blank=True, null=True)),
                ('algorithm', models.TextField(blank=True, null=True)),
                ('pirscan_min_ex_22g_pvalue_corrected', models.FloatField(blank=True, db_column='pirscan min_ex 22G pvalue-corrected', null=True)),
                ('pirscan_max_ex_22g_pvalue_corrected', models.FloatField(blank=True, db_column='pirscan max_ex 22G pvalue-corrected', null=True)),
                ('rnaup_min_ex_22g_pvalue_corrected', models.FloatField(blank=True, db_column='RNAup min_ex 22G pvalue-corrected', null=True)),
                ('rnaup_max_ex_22g_pvalue_corrected', models.FloatField(blank=True, db_column='RNAup max_ex 22G pvalue-corrected', null=True)),
                ('mutation_string', models.TextField(blank=True, null=True)),
                ('prg1mut_wago1_22g_rnaup_min_ex25', models.FloatField(blank=True, db_column='PRG1MUT_WAGO1_22G_RNAup min_ex25', null=True)),
                ('prg1mut_wago1_22g_pirscan_min_ex25', models.FloatField(blank=True, db_column='PRG1MUT_WAGO1_22G_pirscan min_ex25', null=True)),
                ('prg1mut_wago1_22g_rnaup_max_ex25', models.FloatField(blank=True, db_column='PRG1MUT_WAGO1_22G_RNAup max_ex25', null=True)),
                ('prg1mut_wago1_22g_pirscan_max_ex25', models.FloatField(blank=True, db_column='PRG1MUT_WAGO1_22G_pirscan max_ex25', null=True)),
                ('wago1_22g_rnaup_min_ex25_foldchange', models.FloatField(blank=True, db_column='WAGO1_22G_RNAup min_ex25 foldchange', null=True)),
                ('wago1_22g_pirscan_max_ex25_foldchange', models.FloatField(blank=True, db_column='WAGO1_22G_pirscan max_ex25 foldchange', null=True)),
                ('wago1_22g_rnaup_max_ex25_foldchange', models.FloatField(blank=True, db_column='WAGO1_22G_RNAup max_ex25 foldchange', null=True)),
                ('wago1_22g_pirscan_min_ex25_foldchange', models.FloatField(blank=True, db_column='WAGO1_22G_pirscan min_ex25 foldchange', null=True)),
            ],
            options={
                'db_table': 'wtCLASH_hyb_final_web',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WtCrisprWago1FlagIpSrnaSeqBedgraph',
            fields=[
                ('init_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('end_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('evenly_rc', models.CharField(blank=True, max_length=18, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=14, null=True)),
                ('id', models.CharField(db_column='ID', max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'WT_CRISPR_WAGO_1_FLAG_IP_sRNA_seq_bedgraph',
                'managed': False,
            },
        ),
    ]
